import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import Provider from "../../context/Provider";
import UsersContextProvider from "../../context/UserContext";
import TodoContextProvider from "../../context/TodoContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body

        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Provider>
          <UsersContextProvider>
            <Navbar />
            <TodoContextProvider>
              {children}
            </TodoContextProvider>
          </UsersContextProvider>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}